# Generated by Django 5.2.4 on 2025-07-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_presentation_id_alter_presentation_presentation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='presentation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
