# Generated by Django 5.2.4 on 2025-07-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_alter_presentation_presentation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Error'), (1, 'Processing'), (2, 'Completed')], default=0),
        ),
    ]
